### ISSUE TITLE
"Changed items" expands detail items under the section "Passed items" 

### ISSUE THREAD

**Issue by Quramy** [bokuweb/reg-cli#16]
It seems a little strange ...

![ts543qt1kp](https://cloud.githubusercontent.com/assets/1262998/26537749/ce572038-447c-11e7-88b6-c5407c11d07a.gif)

I expect that the "changed items" toggle button expands items under this button itself.

**Comment by bokuweb** [comment]
😭

**Comment by bokuweb** [comment]
I'm gonna fix it....

**Comment by Quramy** [comment]
I've checked out v0.6.3 and this issue was fixed. Thanks 😄

**Comment by bokuweb** [comment]
Thanks!! 🎉
