### ISSUE TITLE
Use image-difference over image-diff

### ISSUE THREAD

**Issue by oliviertassinari** [bokuweb/reg-cli#27]
[image-diff](https://github.com/uber-archive/image-diff) is no longer maintained, I ended up rewriting it with the latest node standard.
[image-difference](https://github.com/argos-ci/image-difference) should run x4 faster based on [the benchmark](https://github.com/argos-ci/image-difference#benchmark).

**Comment by bokuweb** [comment]
@oliviertassinari Thanks for your information!! It looks cool npm module. I gonna try it 👍

**Comment by oliviertassinari** [comment]
Sweet, let me know how that goes. The API changed. It's exposing a Promise over a callback. Also, underlying [magick metric](http://legacy.imagemagick.org/script/command-line-options.php# metric) is exposed as a property. You can pick one between many. image-diff was using `RMSE`. `AE` seems to perform best. I used it as default.

**Comment by bokuweb** [comment]
I will put it on hold, because I can not drop node v6 (image-difference  support node v7+)

**Comment by oliviertassinari** [comment]
I run the tests under v7 and v8. Should be working with v6 too. Will see how that goes.

**Comment by bokuweb** [comment]
I can not install `image-difference` when using node v6, because node engines configured  as `"node": ">= 7.0.0"` in pacakge.json.

 https://github.com/argos-ci/image-difference/blob/master/package.json#L19

**Comment by oliviertassinari** [comment]
I have added the support to node v6.

**Comment by bokuweb** [comment]
Thanks I'll try it.

**Comment by bokuweb** [comment]
@oliviertassinari Thank you for the quick response 👍 
But I have not implemented it yet.
I have tried imageDifference in my env(node v6.9), but reg-cli test has broken.

I guess that `lib/imageDifference.js` contains `async / await` syntax.
Node v6 don't support `async / await`. (need transpile or babel-runtime/babel-polyfill)

e.g.
```
exports.default = async function imageDifference(optionsWithoutDefault) {
...
```

**Comment by bokuweb** [comment]
When I have forked  and rebuild `image-difference`, lib/imageDifference.js is properly transpiled

```
exports.default = (() => {
  var _ref2 = _asyncToGenerator(function* (optionsWithoutDefault) {
    const actualFilename = optionsWithoutDefault.actualFilename,
          expectedFilename = optionsWithoutDefault.expectedFilename;
    var _optionsWithoutDefaul = optionsWithoutDefault.implementation;
```

**Comment by oliviertassinari** [comment]
I could have mess something during the publish. Let me have a look.

**Comment by oliviertassinari** [comment]
> https://github.com/sindresorhus/np/issues/155

Figure it out, TL;DR; thanks npm inc… I have changed the npm hook from `prepublishOnly` to `version.

**Comment by bokuweb** [comment]
it works 🎉 
https://github.com/bokuweb/reg-cli/pull/28

**Comment by bokuweb** [comment]
@oliviertassinari `reg-cli v0.7.0` published.

I create 500 diff images (1280 * 800 png) to create `reg` report using v6.9.0 and v0.7.0.

- v0.6.9 65sec
- v0.7.0 33sec 🎉

**Comment by oliviertassinari** [comment]
🎉
